version: '3.8'

services:
  usermicroservice:
    image: sahilkumardhiman007/usermicroservice:latest
    container_name: usermicroservice
    ports:
      - "5000:5000"
    depends_on:
      - mongodb_service
    environment:
      - MONGODB_URI=mongodb://mongodb_service:27017/ClinicAppointmentSystem
      - CONSULTATIONS_URL=http://consultation-ms:8083
      - APPOINTMENTS_URL=http://appointment-ms:8082
    networks:
      - app_net

  mongodb_service:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_net

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    networks:
      - app_net

  appointment-ms:
    container_name: appointment-ms
    #restart: always
    image: sowmyasantoshi4/appointment-img
    ports:
      - 8082:8082 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
    networks:
      - app_net
  
  consultation-ms:
    container_name: consultation-ms
    #restart: always
    image: sowmyasantoshi4/consultation-img
    ports:
      - 8083:8083 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
    networks:
      - app_net
      
  mysqldb: 
    container_name: mysql-db
    image: mysql
    restart: always
    volumes:
      -  /home/user/Desktop/db:/var/lib/mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: clinicappdb
      MYSQL_USER: clinicappdb
      MYSQL_PASSWORD: clinicappdb
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'C:\mongodb_data'
