version: '3.8'

services:
  usermicroservice:
    image: sahilkumardhiman007/usermicroservice:latest
    container_name: usermicroservice
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/ClinicAppointmentSystem
      - CONSULTATIONS_URL=http://localhost:8083
      - APPOINTMENTS_URL=http://localhost:8082
    networks:
      - app_net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_net

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'C:\mongodb_data'
